### ISSUE TITLE
Getting error when trying to run VM

### ISSUE THREAD

**Issue by dganjali** [wabulu/Single-GPU-passthrough-amd-nvidia#29]
Whenever I try to run the VM, I get this error:
Error starting domain: Cannot recv data: Connection reset by peer

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(args, kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: Cannot recv data: Connection reset by peer

Anyway I can fix this?

**Comment by JoustingZebra** [comment]
I have this problem also.
